Solution
mate-academy/py-move-file pull request #179
Opened 2023-01-31 10:52 UTC by IhorPokr

2023-01-31 11:27 UTC, andrewbelo requested changes

2023-01-31 11:27 UTC, andrewbelo commented on app/main.py
> +    split_command = command.split()
```suggestion
    cmd, src, dst = command.split()
```

2023-01-31 11:27 UTC, andrewbelo commented on app/main.py
> +            new_file = os.path.join(current_path, new_file)
![image](https://user-images.githubusercontent.com/31931886/215747700-f63bd696-15fe-42b3-89d7-19f643abc478.png)
Кросплатформенно має бути

2023-02-01 11:27 UTC, andrewbelo requested changes

2023-02-01 11:27 UTC, andrewbelo commented on app/main.py
> +        if "/" in dst:
В тебе зовсім не має фігурувати слеш в коді

2023-02-01 11:27 UTC, andrewbelo commented on app/main.py
> +        new_file = dst
Якщо тобі ці назви більше подобаються так і назви їх з самого початку

2023-02-01 11:27 UTC, andrewbelo commented on app/main.py
> +        if "/" in dst:
dirname тобі нічого не поверне, якщо це буде на в папці, тому відштовхуйся від цього

2023-02-01 11:27 UTC, andrewbelo commented on app/main.py
> +            new_file = os.path.basename(dst)
є os.path.split, який тобі розділить шлях на папку і файл

2023-02-03 08:27 UTC, andrewbelo requested changes

2023-02-03 08:27 UTC, andrewbelo commented on app/main.py
> +        source_folder, source_filename = os.path.split(src)
Ці змінні ти не юзаєш

2023-02-03 08:27 UTC, andrewbelo commented on app/main.py
> +        new_file = os.path.join(dst_folder, dst_filename)
new_file == dst

2023-02-03 08:27 UTC, andrewbelo commented on app/main.py
> +        source_file = src
це зайвий рядок, якщо хочеш назвати source_file, то вище його так назви відразу

2023-02-03 08:27 UTC, andrewbelo commented on app/main.py
> +            text = file_read.read()
Зайва проміжна змінна

2023-02-05 11:42 UTC, ArsenPidhoretskyi requested changes

2023-02-05 11:42 UTC, ArsenPidhoretskyi commented on app/main.py
> +    _, src, dst = command.split()
1. You must validate the command. Your code will not work with this
command = "mv file1.txt"
command = "mv file1.txt file2.txt file3.txt"
2. Do not use abbreviations use full names. src = source_file_path the same with dst
3. Why you use _ for first? If i say command = "not_mv file1.txt file2.txt" the file will be moved. 
https://github.com/mate-academy/py-move-file/blob/master/checklist.md
Check checklist

2023-02-05 11:42 UTC, ArsenPidhoretskyi commented on app/main.py
> +    new_file = dst
why you need this?

2023-02-05 11:42 UTC, ArsenPidhoretskyi commented on app/main.py
> +            open(new_file, "w") as file_write:
```suggestion
    with (
        open(src, "r") as file_read,
        open(new_file, "w") as file_write
    ):   
```

2023-02-05 11:42 UTC, ArsenPidhoretskyi commented on app/main.py
> +            open(new_file, "w") as file_write:
rename:
 file_read as file_input or source
 file_write as file_output or destination

2023-02-05 12:33 UTC, ArsenPidhoretskyi requested changes

2023-02-05 12:33 UTC, ArsenPidhoretskyi commented on app/main.py
> +    src, dst = command.split()[1:]
Your code will not work with this
command = "mv file1.txt"
command = "mv file1.txt file2.txt file3.txt"
It will fails with unknown error

2023-02-05 12:33 UTC, ArsenPidhoretskyi commented on app/main.py
> +        pass
Is it possible? Can you provide an example for this?

2023-08-31 17:11 UTC, closed without merging