Solution
mate-academy/py-move-file pull request #225
Opened 2023-02-25 23:08 UTC by Sebshe

2023-02-26 13:18 UTC, ArsenPidhoretskyi requested changes

2023-02-26 13:18 UTC, ArsenPidhoretskyi commented on app/main.py
> +    input_command, file, new_file = command.split()
Validate before that command have exactly 3 parameters
Check code for this cases:
mv file1.txt
mv file1.txt file2.txt file3.txt

2023-02-26 15:13 UTC, Bohdan-Salamakha approved these changes

2023-02-27 16:27 UTC, closed without merging

2023-02-27 16:28 UTC, Abnormaltype approved these changes