solution
mate-academy/py-move-file pull request #639
Opened 2024-04-10 16:27 UTC by nrjss67

2024-04-10 17:20 UTC, vsmutok requested changes

2024-04-10 17:20 UTC, vsmutok commented on app/main.py
> +        return
it's better to raise some error in this case so that the user knows if something goes wrong

2024-04-10 17:20 UTC, vsmutok commented on app/main.py
> +        return
I think this is redundant

2024-04-10 17:20 UTC, vsmutok commented on app/main.py
> +        os.replace(file_name, f"{path_without_fn}/{new_file_name}")
why `.txt` ?

What if we need move other type of file? main.py for example

2024-04-10 17:20 UTC, vsmutok requested changes
.

2024-04-11 12:35 UTC, vasylhnatiuk approved these changes

2024-08-05 13:52 UTC, closed without merging